### PR TITLE
ENH add pairwise distances backend for LocalOutlierFactor

### PR DESCRIPTION
**Pull request by OmarManzoor**
#### What does this implement/fix? Explain your changes.
- PR for review and guidance.

#### Any other comments?
CC: @jjerphan Could you kindly have a look at this because I might need some guidance on how to access the indices and distances arrays properly

### CODE REVIEW

**Comment by OmarManzoor** [comment]
@jjerphan I think the part that I might need guidance with is that we actually want the indices and distances computed completely as `dist_k = self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]` we actually need the distances associated with the neighbors as well.

**Comment by jjerphan** [comment]
Those distances are stored in the heaps, so after the execution, it should be possible to access the distances (here `self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`).

Those are technical details that I should probably better document. I think I need some more time.

**Comment by OmarManzoor** [comment]
> Those distances are stored in the heaps, so after the execution, it should be possible to access the distances (here `self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`).
> 
> Those are technical details that I should probably better document. I think I need some more time.

I understand. However I think the point where I added the code is not correct as _parallel_on_X_prange_iter_finalize will not contain the complete X. I think we might need to define this in _finalize where the computation is complete?

**Comment by OmarManzoor** [comment]
> > Those distances are stored in the heaps, so after the execution, it should be possible to access the distances (here `self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`).
> > Those are technical details that I should probably better document. I think I need some more time.
> 
> I understand. However I think the point where I added the code is not correct as _parallel_on_X_prange_iter_finalize will not contain the complete X. I think we might need to define this in _finalize where the computation is complete?

@jjerphan Does it seem correct to include the implementation in the _finalize_results method?

**Comment by jjerphan** [comment]
> @jjerphan Does it seem correct to include the implementation in the _finalize_results method?

Thanks for the heads-up. I think we can first try implementing the logic in `_finalize_results` as you suggest.

**Comment by OmarManzoor** [comment]
@jjerphan I have made changes to accommodate the fit method with the dedicated backend. However there seems to be a complication in the score samples method now. The local reachability density needs the fit distances of the training data X.
`dist_k = self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`

But now since we use a dedicated backend we are not storing these distances anymore and as a result they are not available in the score_samples method.

**Comment by OmarManzoor** [comment]
> @jjerphan I have made changes to accommodate the fit method with the dedicated backend. However there seems to be a complication in the score samples method now. The local reachability density needs the fit distances of the training data X. `dist_k = self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`
> 
> But now since we use a dedicated backend we are not storing these distances anymore and as a result they are not available in the score_samples method.

I would be grateful if you could provide any suggestions. I was thinking about storing the distances in the call to fit but then we would still need these distances when computing score_samples. That would mean the fit distances would need to be available in the ArgKminLRD backend but this kind of creates a difference between how we are using it in fit and score_samples.

**Comment by OmarManzoor** [comment]
> > @jjerphan I have made changes to accommodate the fit method with the dedicated backend. However there seems to be a complication in the score samples method now. The local reachability density needs the fit distances of the training data X. `dist_k = self._distances_fit_X_[neighbors_indices, self.n_neighbors_ - 1]`
> > But now since we use a dedicated backend we are not storing these distances anymore and as a result they are not available in the score_samples method.
> 
> I would be grateful if you could provide any suggestions. I was thinking about storing the distances in the call to fit but then we would still need these distances when computing score_samples. That would mean the fit distances would need to be available in the ArgKminLRD backend but this kind of creates a difference between how we are using it in fit and score_samples.

I just realized we also need self._lrd in score_samples
`lrd_ratios_array = self._lrd[neighbors_indices_X] / X_lrd[:, np.newaxis]`

https://github.com/OmarManzoor/scikit-learn/blob/a9b06a7cbfe3a4f43534a1a840231eb09ec8fb69/sklearn/neighbors/_lof.py#L468-L483

This means that we need to return the lrd from the backend in any case. So we can't compute the negative outlier factor in the backend. But then we would also need to return _neighbors_indices_fit_X_ as they are used to index into self._lrd to calculate lrd_ratios_array in the fit method
https://github.com/OmarManzoor/scikit-learn/blob/a9b06a7cbfe3a4f43534a1a840231eb09ec8fb69/sklearn/neighbors/_lof.py#L290-L307

Looking at this I think we might need to return the neighbor_sample_indices along with lrd.

**Comment by jjerphan** [comment]
Hi @OmarManzoor, must https://github.com/scikit-learn/scikit-learn/pull/26316 be reviewed before this PR? I trying to understand why this branch targets the `main` branch of your fork.

**Comment by OmarManzoor** [comment]
> Hi @OmarManzoor, must [scikit-learn#26316](https://github.com/scikit-learn/scikit-learn/pull/26316) be reviewed before this PR? I trying to understand why this branch targets the `main` branch of your fork.

Closed. This was just for discussion before opening the actual PR on scikit-learn.

**Pull request closed without merging**
