### PR TITLE
PERF Implement PairwiseDistancesReduction backend for RadiusNeighbors.predict_proba

### PR DESCRIPTION
**Pull request by OmarManzoor**

### CODE REVIEW

**Comment by OmarManzoor** [comment]
@jjerphan @Micky774 Just started this work. I just wanted to keep you in the loop so you can have a look at this. I think this is generally going to be similar to Kneighbors with certain adjustments that are required like the outliers.

**Comment by jjerphan** [comment]
Thank you for exploring it, @OmarManzoor! :handshake: 

Before proceeding, I think it makes sense to profile the execution of `RadiusNeighbors.predict_proba` to see if it is worth optimizing (not to loose time as we did in the past with #2 and https://github.com/scikit-learn/scikit-learn/pull/26316).

Also you have selected your fork's `main` branch. Is it intentional?

**Comment by OmarManzoor** [comment]
> Thank you for exploring it, @OmarManzoor! 🤝
> 
> Before proceeding, I think it makes sense to profile the execution of `RadiusNeighbors.predict_proba` to see if it is worth optimizing (not to loose time as we did in the past with #2 and [scikit-learn#26316](https://github.com/scikit-learn/scikit-learn/pull/26316)).
> 
> Also you have selected your fork's `main` branch. Is it intentional?

Yes this is just so we can discuss points and potential approaches before actually creating a PR in scikit learn.

**Comment by OmarManzoor** [comment]
> Thank you for exploring it, @OmarManzoor! 🤝
> 
> Before proceeding, I think it makes sense to profile the execution of `RadiusNeighbors.predict_proba` to see if it is worth optimizing (not to loose time as we did in the past with #2 and [scikit-learn#26316](https://github.com/scikit-learn/scikit-learn/pull/26316)).

I wasn't able to actually successfully profile using the profiler that you had suggested (py-spy). But using timing statements in the code I think this should be quite similar to Kneighbors. Because we are iterating over the classes and the neighbors to calculate the bin counts and the desired probabilities.

**Comment by OmarManzoor** [comment]
Copying the comment I posted from the ticket

Using some simple timeit statements I was able to get the following results

```
--------------------------Iteration 1--------------------------
Start predict probabilities
Time taken by radius_neighbors: 19.6450375
Time taken to compute probabilities: 36.3680472
-----------------------------------------------------------------
--------------------------Iteration 2--------------------------
Start predict probabilities
Time taken by radius_neighbors: 39.5624981
Time taken to compute probabilities: 44.52882960000001
-----------------------------------------------------------------
--------------------------Iteration 3--------------------------
Start predict probabilities
Time taken by radius_neighbors: 29.812655099999972
Time taken to compute probabilities: 43.69632340000004
-----------------------------------------------------------------
And two more iterations in which I ran the complete script again including the fit method.

Time taken by radius_neighbors: 32.9073425
Time taken to compute probabilities: 42.0797534
---------------------------------------------------------------
Start predict probabilities
Time taken by radius_neighbors: 16.559098600000002
Time taken to compute probabilities: 36.1868528
```

Code
<Details of the code>

```python
from sklearn.model_selection import train_test_split
from sklearn.neighbors._classification import RadiusNeighborsClassifier
from sklearn.datasets import make_classification


n_features = 10
n_samples = 50000
n_classes = 100

X, y = make_classification(
    n_samples=n_samples,
    n_features=n_features,
    n_redundant=0,
    n_informative=10,
    n_classes=n_classes,
    random_state=0,
)


X_train, X_test, y_train, _ = train_test_split(X, y, random_state=0)
clf = RadiusNeighborsClassifier(radius=10, algorithm="brute")
clf.fit(X_train, y_train)
for i in range(1, 6):
    print(f"--------------------------Iteration {i}--------------------------")
    print("Start predict probabilities")
    proba = clf.predict_proba(X_test)
    print("-----------------------------------------------------------------")

```

</Details >

**Comment by jjerphan** [comment]
Thanks for the report. It looks like it is worth optimizing `RadiusNeighbors.predict_proba`.

**Comment by Micky774** [comment]
> I wasn't able to actually successfully profile using the profiler that you had suggested (py-spy).

We may want to see if we can fix whatever is going wrong with that. But ditto, all signs point to there being a clear benefit to optimizing this section.

**Comment by OmarManzoor** [comment]
@jjerphan @Micky774 I have added the main code. I think before refining this and adding tests how about we run some benchmarks here?

**Comment by jjerphan** [comment]
Yes, please reuse the asv benchmark scripts.

**Comment by OmarManzoor** [comment]
> Yes, please reuse the asv benchmark scripts.

Yeah did that exactly but when I ran on a larger set of data, it results in memory errors like
`python(17542,0x1f03e5e00) malloc: Incorrect checksum for freed object 0x135827000: probably modified after being freed.`
`segmentation fault`

**Comment by OmarManzoor** [comment]
> > Yes, please reuse the asv benchmark scripts.
> 
> Yeah I did that exactly but when I ran on a larger set of data, it results in memory errors like 
```
python(17542,0x1f03e5e00) malloc: Incorrect checksum for freed object 0x135827000: probably modified after being freed.
```
or

`segmentation fault`

**Comment by jjerphan** [comment]
Could you craft a minimal reproducer ?

**Comment by jjerphan** [comment]
Could you craft a minimal reproducer?

**Comment by OmarManzoor** [comment]
> Could you craft a minimal reproducer?

https://gist.github.com/OmarManzoor/4ccf778046b66ddc02122d7db1f61d76

Might have something to do with how I am using vector or how I am using the heap/vector structures in _parallel_on_X_prange_iter_finalize.

**Comment by jjerphan** [comment]
To understand the double free, You can try to use `asan` if you are using `clang` otherwise you can debug using `gdb --args python script.py`. I recommend forcing using a single thread to debug (this can be done with `taskset(1)` on Linux).

**Comment by jjerphan** [comment]
You can try to use `asan` if you are using `clang` otherwise you can debug using `gdb --args python script.py`. I recommend forcing using a single thread to debug (this can be done with `taskset(1)` on Linux).

**Comment by OmarManzoor** [comment]
> You can try to use `asan` if you are using `clang` otherwise you can debug using `gdb --args python script.py`. I recommend forcing using a single thread to debug (this can be done with `taskset(1)` on Linux).

I am on on Mac M1 now. Any idea which of the above would work with M1?

**Comment by OmarManzoor** [comment]
```console
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[ 0.00%] · For scikit-learn commit 0ad31271 <radius_neighbors_predict_pwdb> (round 1/1):
[ 0.00%] ·· Benchmarking conda-py3.11-cython-joblib-numpy-pandas-scipy-threadpoolctl
[50.00%] ··· radius_neighbors_predict.BruteRadiusNeighborsClass.time_predict_proba                                                                                  ok
[50.00%] ··· ========= ============
             --        n_test / n_features
             --------- ------------
              n_train   1000 / 100 
             ========= ============
               10000     195±20ms  
             ========= ============

[50.00%] · For scikit-learn commit dfd299b1 (round 1/1):
[50.00%] ·· Building for conda-py3.11-cython-joblib-numpy-pandas-scipy-threadpoolctl.
[50.00%] ·· Benchmarking conda-py3.11-cython-joblib-numpy-pandas-scipy-threadpoolctl
[100.00%] ··· radius_neighbors_predict.BruteRadiusNeighborsClass.time_predict_proba                                                                                  ok
[100.00%] ··· ========= ============
              --        n_test / n_features
              --------- ------------
               n_train   1000 / 100 
              ========= ============
                10000     226±20ms  
              ========= ============

| Change   | Before [dfd299b1]    | After [0ad31271] <radius_neighbors_predict_pwdb>   |   Ratio | Benchmark (Parameter)                                                                   |
|----------|----------------------|----------------------------------------------------|---------|-----------------------------------------------------------------------------------------|
| -        | 226±20ms             | 195±20ms                                           |    0.86 | radius_neighbors_predict.BruteRadiusNeighborsClass.time_predict_proba(10000, 1000, 100) |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE INCREASED.

```

ASV Benchmark: https://gist.github.com/OmarManzoor/444ee05b9c902ca795fc7e377f4d5714

**Comment by jjerphan** [comment]
Thanks for reporting the results. For now, the test suites' aren't run on your fork.

You can either:
 - adapt the CI configurations (one need to alter _at least_ [some of the lines of the CI configuration](https://github.com/search?q=repo%3Ascikit-learn%2Fscikit-learn+%22scikit-learn%2Fscikit-learn%22++path%3A.github&type=code) and [this one from Cirrus CI](https://github.com/scikit-learn/scikit-learn/blob/dfd299b19e1e4a167023cac76c8e1c57c01341a9/.cirrus.star#L9)) so that test suites' run on your fork
 - create a Draft PR upstream (I would recommend this option for simplicity and to make this PR discoverable).

**Comment by OmarManzoor** [comment]
> https://gist.github.com/OmarManzoor/444ee05b9c902ca795fc7e377f4d5714

Yes I think we should make a PR on scikit learn now. This was just the initial work and a performance experiment.

**Pull request closed without merging**
